#!/usr/bin/env bash
#
# install-cron.sh — Install a weekly cron job that runs maintenance.sh.
#
# Creates /etc/cron.weekly/yb-maintenance + a logrotate config for its log.
# The cron entry fetches the latest scripts from origin (best-effort) and
# then runs scripts/maintenance.sh, appending output to /var/log/yb-maintenance.log.
#
# Run this from the cloned repo on the target server:
#   sudo bash scripts/install-cron.sh
#   sudo bash scripts/install-cron.sh --uninstall
#
set -euo pipefail

UNINSTALL=0
[[ "${1:-}" == "--uninstall" ]] && UNINSTALL=1

if [[ $EUID -ne 0 ]]; then
  echo "Run as root (sudo bash $0)" >&2
  exit 1
fi

CRON_FILE=/etc/cron.weekly/yb-maintenance
LOG_FILE=/var/log/yb-maintenance.log
LOGROTATE_FILE=/etc/logrotate.d/yb-maintenance

if [[ $UNINSTALL -eq 1 ]]; then
  [[ -f $CRON_FILE ]]      && rm -v "$CRON_FILE"      || echo "no $CRON_FILE"
  [[ -f $LOGROTATE_FILE ]] && rm -v "$LOGROTATE_FILE" || echo "no $LOGROTATE_FILE"
  echo "Uninstalled. Log file $LOG_FILE preserved (delete manually if you want)."
  exit 0
fi

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ ! -f "$REPO_DIR/scripts/maintenance.sh" ]]; then
  echo "ERROR: $REPO_DIR/scripts/maintenance.sh not found." >&2
  echo "Run this installer from inside the cloned repository." >&2
  exit 1
fi

if [[ ! -d "$REPO_DIR/.git" ]]; then
  echo "ERROR: $REPO_DIR is not a git working tree." >&2
  exit 1
fi

if [[ ! -d /etc/cron.weekly ]]; then
  echo "ERROR: /etc/cron.weekly does not exist (cron/anacron not installed?)." >&2
  exit 1
fi

# cron.weekly entries must have NO file extension on Debian/Ubuntu (run-parts
# rejects anything matching a regex that excludes dots).
cat > "$CRON_FILE" <<EOF
#!/bin/sh
# Auto-generated by $REPO_DIR/scripts/install-cron.sh — do not edit by hand.
# Re-run the installer to regenerate.

set -e

cd "$REPO_DIR"

# Best-effort pull. If the remote is unreachable or auth is missing, fall back
# to whatever is currently checked out. "safe.directory=*" suppresses the
# "dubious ownership" guard since this runs as root against a tree owned by
# whoever cloned it.
git -c safe.directory='*' pull --quiet --ff-only 2>/dev/null || true

{
  echo "=== \$(date -Iseconds) maintenance start ==="
  bash scripts/maintenance.sh
  echo "=== \$(date -Iseconds) maintenance end ==="
} >> "$LOG_FILE" 2>&1
EOF
chmod 755 "$CRON_FILE"

touch "$LOG_FILE"
chmod 640 "$LOG_FILE"
chown root:adm "$LOG_FILE" 2>/dev/null || chown root:root "$LOG_FILE"

cat > "$LOGROTATE_FILE" <<EOF
$LOG_FILE {
    weekly
    rotate 8
    compress
    delaycompress
    missingok
    notifempty
    create 640 root adm
}
EOF
chmod 644 "$LOGROTATE_FILE"

cat <<EOF

Installed:
  cron entry      $CRON_FILE
  log file        $LOG_FILE
  logrotate conf  $LOGROTATE_FILE (keeps 8 weekly rotations, compressed)

Schedule:
  Runs via /etc/cron.weekly — anacron picks a randomised time once a week.
  See /etc/anacrontab for the exact window.

Verify now (does NOT wait for the schedule):
  sudo run-parts --test /etc/cron.weekly        # confirms cron picks it up
  sudo bash $CRON_FILE                          # runs it once immediately
  sudo tail -f $LOG_FILE                        # follow the log

Uninstall:
  sudo bash $REPO_DIR/scripts/install-cron.sh --uninstall
EOF
